export const DataLastestEpisodes = [
	{
		img : "./imges/campbell-3ZUsNJhi_Ik-unsplash_opt.jpg" , 
		time : "DECEMBER 6, 2021" , 
		title : "Episode 203 - The Last Blockbuster" , 
		like : 23 , 
		share : 44 , 
		down : 19 , 
	} ,
	{
		img : "./imges/nick-karvounis-aT2p0zMuqPM-unsplash_opt.jpg" ,
		time : "DECEMBER 6, 2021" , 
		title : "Episode 203 - The Last Blockbuster" , 
		like : 23 , 
		share : 44 , 
		down : 19 , 
	} , 
	{
		img : "./imges/fachry-zella-devandra-WG9v_36blYI-unsplash_opt.jpg" ,
		time : "DECEMBER 6, 2021" , 
		title : "Episode 203 - The Last Blockbuster" , 
		like : 23 , 
		share : 44 , 
		down : 19 , 
	} ,
	{
		img : "./imges/josh-garcia-_87wQoFZDPA-unsplash_opt.jpg" , 
		time : "DECEMBER 6, 2021" , 
		title : "Episode 203 - The Last Blockbuster" , 
		like : 23 , 
		share : 44 , 
		down : 19 , 
	} , 
		{
		img : "./imges/luke-porter-ohBhECoxQoU-unsplash_opt.jpg" , 
		time : "DECEMBER 6, 2021" , 
		title : "Episode 203 - The Last Blockbuster" , 
		like : 23 , 
		share : 44 , 
		down : 19 , 
	} ,
	{
		img : "./imges/marek-rucinski-WnUyhtAVZW0-unsplash_opt.jpg" , 
		time : "DECEMBER 6, 2021" , 
		title : "Episode 203 - The Last Blockbuster" , 
		like : 23 , 
		share : 44 , 
		down : 19 , 
	}
] 